apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.labels.app }}
